.PHONY: help build clean db-bootstrap db-migrate-prod deploy-web-prod dev e2e format install knip lighthouse lint lint-ci lint-fix preflight security test test-coverage typecheck

# Default target
help:
	@echo "Fat Bear Week Fantasy Bracket"
	@echo ""
	@echo "Usage: make <target>"
	@echo ""
	@echo "Setup:"
	@echo "  install          Install root (husky) + web dependencies"
	@echo ""
	@echo "Database:"
	@echo "  db-bootstrap     Generate database/bootstrap.sql (all migrations in one file)"
	@echo "  db-migrate-prod  Show how to run migrations on Supabase"
	@echo ""
	@echo "Development:"
	@echo "  build            Build Next.js for production"
	@echo "  dev              Start Next.js dev server"
	@echo ""
	@echo "Quality:"
	@echo "  format           Autofix lint issues (ESLint --fix)"
	@echo "  lint             Run ESLint"
	@echo "  lint-ci          Same as lint-fix (used in CI after format)"
	@echo "  lint-fix        Run ESLint with --fix"
	@echo "  typecheck        TypeScript --noEmit"
	@echo "  knip             Unused files / dependencies"
	@echo "  preflight        format + lint + typecheck + knip + test + security + build"
	@echo ""
	@echo "Security:"
	@echo "  security         npm audit on production dependencies"
	@echo ""
	@echo "Testing:"
	@echo "  test             Run Vitest with coverage thresholds"
	@echo "  test-coverage    Alias for test"
	@echo "  e2e              Cypress smoke (starts Next.js, then runs cypress)"
	@echo "  lighthouse       Build + LHCI against next start (mobile)"
	@echo ""
	@echo "Deploy:"
	@echo "  deploy-web-prod  Merge main into release and push (promotes web to production)"
	@echo "  (Deploy web to Preview: push to main, e.g. git push origin main)"
	@echo ""
	@echo "Utilities:"
	@echo "  clean            Remove generated files and caches"

# Database
db-bootstrap:
	@echo "Generating database/bootstrap.sql (all migrations in order)..."
	@mkdir -p database
	@(echo "-- Generated by 'make db-bootstrap'. Source: database/migrations/ (all files in sorted order). Do not edit by hand."; echo ""; for f in $$(ls database/migrations/*.sql | sort -V); do cat "$$f"; done) > database/bootstrap.sql
	@echo "Done. Run database/bootstrap.sql once in Supabase SQL Editor for a new project."
	@echo "After adding a new migration, run 'make db-bootstrap' again and commit the updated file."

db-migrate-prod:
	@echo "=============================================="
	@echo "  SUPABASE MIGRATION INSTRUCTIONS"
	@echo "=============================================="
	@echo ""
	@echo "New project (no schema yet): Run database/bootstrap.sql once in SQL Editor."
	@echo "Existing project: Run only migration files not yet applied, in numeric order."
	@echo "Full wipe: database/scripts/drop_all_tables.sql then bootstrap."
	@echo ""
	@echo "See docs/SUPABASE_MIGRATIONS.md for details."
	@echo ""
	@echo "=============================================="

# Install dependencies
install:
	npm install
	cd web && npm install --legacy-peer-deps

# Development
build:
	cd web && npm run build

dev:
	cd web && npm run dev

# Linting / types
lint:
	cd web && npm run lint

lint-fix:
	cd web && npm run lint:fix

lint-ci: lint-fix

format: lint-fix

typecheck:
	cd web && npm run typecheck

knip:
	cd web && npm run knip

preflight:
	./scripts/preflight.sh

# Security
security:
	@echo "Running npm audit on production dependencies..."
	cd web && npm audit --omit=dev

# Testing
test:
	cd web && npm test

test-coverage: test

e2e:
	cd web && npm run e2e

# Requires Chrome/Chromium. Builds first, then LHCI starts `next start`.
lighthouse: build
	cd web && npm run lighthouse

# Deploy
deploy-web-prod:
	@if git status --porcelain | grep -q .; then \
		echo "Error: uncommitted changes; commit or stash first"; \
		exit 1; \
	fi
	git checkout release && \
	git pull origin release && \
	git merge main --no-edit && \
	git push origin release && \
	git checkout main

# Utilities
clean:
	find . -type d -name "node_modules" -exec rm -rf {} + 2>/dev/null || true
	find . -type d -name ".next" -exec rm -rf {} + 2>/dev/null || true
	find . -type d -name "coverage" -exec rm -rf {} + 2>/dev/null || true
