.PHONY: help build clean db-bootstrap db-migrate-prod deploy-web-prod dev format install lint lint-ci lint-fix security test test-coverage

# Default target
help:
	@echo "Fat Bear Week Fantasy Bracket"
	@echo ""
	@echo "Usage: make <target>"
	@echo ""
	@echo "Setup:"
	@echo "  install          Install web dependencies"
	@echo ""
	@echo "Database:"
	@echo "  db-bootstrap     Generate database/bootstrap.sql (all migrations in one file)"
	@echo "  db-migrate-prod  Show how to run migrations on Supabase"
	@echo ""
	@echo "Development:"
	@echo "  build            Build Next.js for production"
	@echo "  dev              Start Next.js dev server"
	@echo ""
	@echo "Quality:"
	@echo "  format           Autofix lint issues (ESLint --fix)"
	@echo "  lint             Run ESLint"
	@echo "  lint-ci          Same as lint-fix (used in CI after format)"
	@echo "  lint-fix        Run ESLint with --fix"
	@echo ""
	@echo "Security:"
	@echo "  security         Run npm audit"
	@echo ""
	@echo "Testing:"
	@echo "  test             Run Vitest"
	@echo "  test-coverage    Run Vitest with coverage"
	@echo ""
	@echo "Deploy:"
	@echo "  deploy-web-prod  Merge main into release and push (promotes web to production)"
	@echo "  (Deploy web to Preview: push to main, e.g. git push origin main)"
	@echo ""
	@echo "Utilities:"
	@echo "  clean            Remove generated files and caches"

# Database
db-bootstrap:
	@echo "Generating database/bootstrap.sql (all migrations in order)..."
	@mkdir -p database
	@(echo "-- Generated by 'make db-bootstrap'. Source: database/migrations/ (all files in sorted order). Do not edit by hand."; echo ""; for f in $$(ls database/migrations/*.sql | sort -V); do cat "$$f"; done) > database/bootstrap.sql
	@echo "Done. Run database/bootstrap.sql once in Supabase SQL Editor for a new project."
	@echo "After adding a new migration, run 'make db-bootstrap' again and commit the updated file."

db-migrate-prod:
	@echo "=============================================="
	@echo "  SUPABASE MIGRATION INSTRUCTIONS"
	@echo "=============================================="
	@echo ""
	@echo "New project (no schema yet): Run database/bootstrap.sql once in SQL Editor."
	@echo "Existing project: Run only migration files not yet applied, in numeric order."
	@echo ""
	@echo "See docs/SUPABASE_MIGRATIONS.md for details."
	@echo ""
	@echo "=============================================="

# Install dependencies
install:
	cd web && npm install --legacy-peer-deps

# Development
build:
	cd web && npm run build

dev:
	cd web && npm run dev

# Linting
lint:
	cd web && npm run lint

lint-fix:
	cd web && npm run lint:fix

lint-ci: lint-fix

format: lint-fix

# Security
security:
	@echo "Running npm audit (dependency vulnerabilities)..."
	cd web && npm audit

# Testing
test:
	cd web && npm test

test-coverage:
	cd web && npm run test:coverage

# Deploy
deploy-web-prod:
	@if git status --porcelain | grep -q .; then \
		echo "Error: uncommitted changes; commit or stash first"; \
		exit 1; \
	fi
	git checkout release && \
	git pull origin release && \
	git merge main --no-edit && \
	git push origin release && \
	git checkout main

# Utilities
clean:
	find . -type d -name "node_modules" -exec rm -rf {} + 2>/dev/null || true
	find . -type d -name ".next" -exec rm -rf {} + 2>/dev/null || true
	find . -type d -name "coverage" -exec rm -rf {} + 2>/dev/null || true
