-- Generated by 'make db-bootstrap'. Source: database/migrations/ (all files in sorted order). Do not edit by hand.

-- 001_initial_schema.sql
-- Fat Bear Week Fantasy Bracket — initial schema
-- Conventions: UUID PKs, TIMESTAMPTZ, created_at/updated_at on mutable tables

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ---------------------------------------------------------------------------
-- updated_at helper
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------------

CREATE TABLE users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  email TEXT,
  password_hash TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX users_email_unique ON users (email) WHERE email IS NOT NULL;

-- ---------------------------------------------------------------------------
-- pools
-- ---------------------------------------------------------------------------

CREATE TABLE pools (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  invite_prefix TEXT,
  max_players INTEGER NOT NULL DEFAULT 100 CHECK (max_players > 0),
  bracket_deadline TIMESTAMPTZ,
  scoring_system TEXT NOT NULL DEFAULT 'standard_1_2_4_8',
  show_brackets_before_lock BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER pools_updated_at
  BEFORE UPDATE ON pools
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ---------------------------------------------------------------------------
-- tournaments
-- ---------------------------------------------------------------------------

CREATE TABLE tournaments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  year INTEGER NOT NULL UNIQUE,
  status TEXT NOT NULL DEFAULT 'draft'
    CHECK (status IN ('complete', 'draft', 'live', 'locked')),
  starts_at TIMESTAMPTZ,
  ends_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER tournaments_updated_at
  BEFORE UPDATE ON tournaments
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ---------------------------------------------------------------------------
-- bears
-- ---------------------------------------------------------------------------

CREATE TABLE bears (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  official_id TEXT,
  number INTEGER,
  name TEXT NOT NULL,
  nickname TEXT,
  description TEXT,
  image_url TEXT,
  profile_url TEXT,
  age INTEGER,
  sex TEXT CHECK (sex IS NULL OR sex IN ('female', 'male', 'unknown')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX bears_number_idx ON bears (number);
CREATE UNIQUE INDEX bears_official_id_unique ON bears (official_id)
  WHERE official_id IS NOT NULL;

CREATE TRIGGER bears_updated_at
  BEFORE UPDATE ON bears
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ---------------------------------------------------------------------------
-- matchups
-- ---------------------------------------------------------------------------

CREATE TABLE matchups (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tournament_id UUID NOT NULL REFERENCES tournaments (id) ON DELETE CASCADE,
  round INTEGER NOT NULL CHECK (round >= 1),
  position INTEGER NOT NULL CHECK (position >= 0),
  bear_a_id UUID REFERENCES bears (id) ON DELETE SET NULL,
  bear_b_id UUID REFERENCES bears (id) ON DELETE SET NULL,
  winner_id UUID REFERENCES bears (id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'upcoming'
    CHECK (status IN ('complete', 'upcoming', 'voting')),
  official_votes_a INTEGER CHECK (official_votes_a IS NULL OR official_votes_a >= 0),
  official_votes_b INTEGER CHECK (official_votes_b IS NULL OR official_votes_b >= 0),
  starts_at TIMESTAMPTZ,
  ends_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (tournament_id, round, position)
);

CREATE INDEX matchups_tournament_id_idx ON matchups (tournament_id);
CREATE INDEX matchups_status_idx ON matchups (status);

CREATE TRIGGER matchups_updated_at
  BEFORE UPDATE ON matchups
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ---------------------------------------------------------------------------
-- invitations (individual, curated invite tokens)
-- ---------------------------------------------------------------------------

CREATE TABLE invitations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  pool_id UUID NOT NULL REFERENCES pools (id) ON DELETE CASCADE,
  token TEXT NOT NULL UNIQUE,
  name_hint TEXT,
  used_by UUID REFERENCES users (id) ON DELETE SET NULL,
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX invitations_pool_id_idx ON invitations (pool_id);
CREATE INDEX invitations_used_by_idx ON invitations (used_by);

-- ---------------------------------------------------------------------------
-- entries (one bracket per user per pool)
-- ---------------------------------------------------------------------------

CREATE TABLE entries (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  pool_id UUID NOT NULL REFERENCES pools (id) ON DELETE CASCADE,
  tiebreaker_answer INTEGER,
  submitted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, pool_id)
);

CREATE INDEX entries_pool_id_idx ON entries (pool_id);

-- ---------------------------------------------------------------------------
-- picks
-- ---------------------------------------------------------------------------

CREATE TABLE picks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  entry_id UUID NOT NULL REFERENCES entries (id) ON DELETE CASCADE,
  matchup_id UUID NOT NULL REFERENCES matchups (id) ON DELETE CASCADE,
  bear_id UUID NOT NULL REFERENCES bears (id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (entry_id, matchup_id)
);

CREATE INDEX picks_entry_id_idx ON picks (entry_id);
CREATE INDEX picks_matchup_id_idx ON picks (matchup_id);
